const data = {
  chartImage:
    "https://storage.googleapis.com/freshtracks-public-folder/other/27-1716562409359-logo.png",
  fund_logo_imgurl:
    "https://storage.googleapis.com/freshtracks_public/other/AICo-1727718322184.png",
  company_data: [
    {
      id: "5511",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "AICo",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: 0,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: "openai.com",
      ESOPSizeTotal: null,
      Currency: null,
      Industry: "Software",
      Country: "Canada",
      ImpairedDiscount: null,
      tags: [
        {
          id: "62",
          __typename: "Tag",
          Name: "AI Focus",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
        {
          id: "63",
          __typename: "Tag",
          Name: "Female Led",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
      ],
      Logo: {
        id: "1848",
        __typename: "UploadFile",
        url: "https://storage.googleapis.com/freshtracks_public/other/AICo-1727718322184.png",
        width: 128,
        height: 128,
      },
      company_details: [
        {
          id: "14493",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5511" },
          EffectiveDate: "2024-03-04T05:00:00.000Z",
          SharePrice: null,
          Discount: null,
          Currency: null,
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: true,
          DiscountFixedValue: null,
        },
        {
          id: "14494",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5511" },
          EffectiveDate: "2024-03-04T05:00:00.000Z",
          SharePrice: 15,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
        },
        {
          id: "14492",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5511" },
          EffectiveDate: "2024-02-01T05:00:00.000Z",
          SharePrice: 13,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
        },
        {
          id: "14491",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5511" },
          EffectiveDate: "2022-02-01T05:00:00.000Z",
          SharePrice: 7.5,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
        },
      ],
      distributions: [
        {
          id: "2234",
          __typename: "Distribution",
          Name: "Secondary",
          Amount: 400000,
          DistributionDate: "2024-02-01T05:00:00.000Z",
          EarnoutPaymentDate: null,
          ShareCompanyName: null,
          SharesSold: 40000,
          SharePrice: 0,
          Currency: "CAD",
          Type: "Cash",
          FX: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      investments: [
        {
          id: "10391",
          __typename: "Investment",
          Name: "Seed Round",
          Amount: 750000,
          CloseDate: "2022-02-01T05:00:00.000Z",
          NumberOfSharesActual: 100000,
          NumberOfOptionsActual: 0,
          Type: "Equity",
          InterestRate: 0,
          ConvertedToEquity: false,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: 7.5,
          Currency: "CAD",
          Cap: 0,
          Discount: 0,
          FX: null,
          StrikePrice: 0,
          StrikePriceCurrency: "CAD",
          ConvertibleValue: null,
          NotePriceDifferFromValue: false,
          InterestRateCompounding: "Annually",
          ClassName: "SeriesA",
          Series: "N1",
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 750000,
      total_irr_disp: 19.2586391978967,
      moic: 1.5333333333333334,
      total_remaining_value_disp: 750000,
      total_distributed_all_cos_disp: 400000,
      SharePriceHistory: [
        { SharePrice: 7.5, Currency: "CAD", Date: "2022-02-01T05:00:00.000Z" },
        { SharePrice: 13, Currency: "CAD", Date: "2024-02-01T05:00:00.000Z" },
        { SharePrice: 15, Currency: "CAD", Date: "2024-03-04T05:00:00.000Z" },
      ],
      DiscountHistory: [
        {
          Discount: null,
          Date: "2024-03-04T05:00:00.000Z",
          DiscountToCost: true,
        },
      ],
      metric_details: [],
      logo_imgurl:
        "https://storage.googleapis.com/freshtracks_public/other/AICo-1727718322184.png",
    },
    {
      id: "5521",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "BuyProperly Limited",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: null,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: null,
      ESOPSizeTotal: null,
      Currency: null,
      Industry: null,
      Country: null,
      ImpairedDiscount: null,
      tags: [],
      Logo: null,
      company_details: [
        {
          id: "14508",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5521" },
          EffectiveDate: "2024-10-01T04:00:00.000Z",
          SharePrice: null,
          Discount: null,
          Currency: "USD",
          CashRemaining: 2000000,
          Burn: 10000,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: "2mm in cash remaining and 10k burn",
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
          MonthsOfRunway: "200.0",
        },
      ],
      distributions: [],
      investments: [
        {
          id: "10397",
          __typename: "Investment",
          Name: "BuyProperly Limited - SAFE",
          Amount: 50000,
          CloseDate: "2020-09-21T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "CAD",
          Cap: 5000000,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
        {
          id: "10398",
          __typename: "Investment",
          Name: "BuyProperly Limited - SAFE",
          Amount: 50000,
          CloseDate: "2020-09-21T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "CAD",
          Cap: 5000000,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 100000,
      total_irr_disp: 0,
      moic: 1,
      total_remaining_value_disp: 100000,
      total_distributed_all_cos_disp: 0,
      SharePriceHistory: [],
      DiscountHistory: [],
      metric_details: [
        {
          id: "14508",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5521" },
          EffectiveDate: "2024-10-01T04:00:00.000Z",
          SharePrice: null,
          Discount: null,
          Currency: "USD",
          CashRemaining: 2000000,
          Burn: 10000,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: "2mm in cash remaining and 10k burn",
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
          MonthsOfRunway: "200.0",
        },
      ],
      logo_imgurl: "",
    },
    {
      id: "5525",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "FunnelX",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: null,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: null,
      ESOPSizeTotal: null,
      Currency: null,
      Industry: null,
      Country: null,
      ImpairedDiscount: null,
      tags: [],
      Logo: null,
      company_details: [],
      distributions: [
        {
          id: "2239",
          __typename: "Distribution",
          Name: "Distribution from chat",
          Amount: 100,
          DistributionDate: "2024-10-01T04:00:00.000Z",
          EarnoutPaymentDate: null,
          ShareCompanyName: null,
          SharesSold: null,
          SharePrice: null,
          Currency: "USD",
          Type: "Cash",
          FX: 1.23,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      investments: [
        {
          id: "10403",
          __typename: "Investment",
          Name: "FunnelX - SAFE",
          Amount: 100000,
          CloseDate: "2020-05-01T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "USD",
          Cap: null,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 100000,
      total_irr_disp: 7.031291738304479,
      moic: 1.3507499599409236,
      total_remaining_value_disp: 134951.99599409237,
      total_distributed_all_cos_disp: 123,
      SharePriceHistory: [],
      DiscountHistory: [],
      metric_details: [],
      logo_imgurl: "",
    },
    {
      id: "5524",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "Heirlume",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: null,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: null,
      ESOPSizeTotal: null,
      Currency: null,
      Industry: null,
      Country: null,
      ImpairedDiscount: null,
      tags: [],
      Logo: null,
      company_details: [],
      distributions: [],
      investments: [
        {
          id: "10400",
          __typename: "Investment",
          Name: "Heirlume - SAFE",
          Amount: 100000,
          CloseDate: "2021-04-05T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "CAD",
          Cap: 8000000,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
        {
          id: "10401",
          __typename: "Investment",
          Name: "Heirlume - SAFE",
          Amount: 100000,
          CloseDate: "2021-04-05T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "CAD",
          Cap: 8000000,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 200000,
      total_irr_disp: 0,
      moic: 1,
      total_remaining_value_disp: 200000,
      total_distributed_all_cos_disp: 0,
      SharePriceHistory: [],
      DiscountHistory: [],
      metric_details: [],
      logo_imgurl: "",
    },
    {
      id: "5512",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "NewCo",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: 0,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: "nba.com",
      ESOPSizeTotal: null,
      Currency: null,
      Industry: "Software",
      Country: "Canada",
      ImpairedDiscount: null,
      tags: [],
      Logo: {
        id: "1849",
        __typename: "UploadFile",
        url: "https://storage.googleapis.com/freshtracks_public/other/NewCo-1727718322707.png",
        width: 128,
        height: 128,
      },
      company_details: [
        {
          id: "14496",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5512" },
          EffectiveDate: "2024-05-14T04:00:00.000Z",
          SharePrice: 33,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
        },
        {
          id: "14495",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5512" },
          EffectiveDate: "2024-02-17T05:00:00.000Z",
          SharePrice: 10,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
        },
      ],
      distributions: [
        {
          id: "2235",
          __typename: "Distribution",
          Name: "NewDist",
          Amount: 100000,
          DistributionDate: "2024-03-07T05:00:00.000Z",
          EarnoutPaymentDate: null,
          ShareCompanyName: null,
          SharesSold: 1,
          SharePrice: 0,
          Currency: "CAD",
          Type: "Cash",
          FX: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      investments: [
        {
          id: "10393",
          __typename: "Investment",
          Name: "SAFE",
          Amount: 100000,
          CloseDate: "2023-12-01T05:00:00.000Z",
          NumberOfSharesActual: 0,
          NumberOfOptionsActual: 0,
          Type: "SAFE",
          InterestRate: 6,
          ConvertedToEquity: true,
          ConvertedDate: "2024-03-07T05:00:00.000Z",
          Maturity: null,
          PricePerUnit: 0,
          Currency: "CAD",
          Cap: 0,
          Discount: 0,
          FX: null,
          StrikePrice: 0,
          StrikePriceCurrency: "CAD",
          ConvertibleValue: null,
          NotePriceDifferFromValue: false,
          InterestRateCompounding: "Annually",
          ClassName: "SeriesA",
          Series: "N1",
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
        {
          id: "10392",
          __typename: "Investment",
          Name: "New Investment",
          Amount: null,
          CloseDate: "2024-02-17T05:00:00.000Z",
          NumberOfSharesActual: 10000,
          NumberOfOptionsActual: 0,
          Type: "Equity",
          InterestRate: 0,
          ConvertedToEquity: false,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: 0,
          Currency: "CAD",
          Cap: 0,
          Discount: 0,
          FX: null,
          StrikePrice: 0,
          StrikePriceCurrency: "CAD",
          ConvertibleValue: null,
          NotePriceDifferFromValue: false,
          InterestRateCompounding: "Annually",
          ClassName: "SeriesA",
          Series: "N1",
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 100000,
      total_irr_disp: 939.9132984140083,
      moic: 4.29967,
      total_remaining_value_disp: 329967,
      total_distributed_all_cos_disp: 100000,
      SharePriceHistory: [
        { SharePrice: 10, Currency: "CAD", Date: "2024-02-17T05:00:00.000Z" },
        { SharePrice: 33, Currency: "CAD", Date: "2024-05-14T04:00:00.000Z" },
      ],
      DiscountHistory: [],
      metric_details: [],
      logo_imgurl:
        "https://storage.googleapis.com/freshtracks_public/other/NewCo-1727718322707.png",
    },
    {
      id: "5509",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "Nvidia",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: null,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: "nvidia.com",
      ESOPSizeTotal: null,
      Currency: null,
      Industry: null,
      Country: "United States of America",
      ImpairedDiscount: null,
      tags: [
        {
          id: "63",
          __typename: "Tag",
          Name: "Female Led",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
        {
          id: "64",
          __typename: "Tag",
          Name: "Deep Tech",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
        {
          id: "62",
          __typename: "Tag",
          Name: "AI Focus",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
      ],
      Logo: {
        id: "1846",
        __typename: "UploadFile",
        url: "https://storage.googleapis.com/freshtracks_public/other/Nvidia-1727718320796.png",
        width: 128,
        height: 128,
      },
      company_details: [
        {
          id: "14489",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5509" },
          EffectiveDate: "2024-05-14T04:00:00.000Z",
          SharePrice: 35,
          Discount: null,
          Currency: "USD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
        },
        {
          id: "14488",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5509" },
          EffectiveDate: "2024-02-16T05:00:00.000Z",
          SharePrice: 15,
          Discount: null,
          Currency: "USD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
        },
        {
          id: "14487",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5509" },
          EffectiveDate: "2023-01-11T05:00:00.000Z",
          SharePrice: 10,
          Discount: null,
          Currency: "USD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
        },
        {
          id: "14486",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5509" },
          EffectiveDate: "2021-02-01T05:00:00.000Z",
          SharePrice: 1,
          Discount: null,
          Currency: "CAD",
          CashRemaining: null,
          Burn: null,
          MRR: null,
          Headcount: null,
          ActiveUsers: null,
          ActiveCustomers: null,
          ActiveCustomerDescriptor: null,
          UpdateNote: null,
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: null,
          DiscountFixedValue: null,
        },
      ],
      distributions: [
        {
          id: "2233",
          __typename: "Distribution",
          Name: "Small Sale",
          Amount: 350000,
          DistributionDate: "2024-05-14T04:00:00.000Z",
          EarnoutPaymentDate: null,
          ShareCompanyName: null,
          SharesSold: 10000,
          SharePrice: 0,
          Currency: "USD",
          Type: "Cash",
          FX: 1.4035,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      investments: [
        {
          id: "10389",
          __typename: "Investment",
          Name: "Seed Round",
          Amount: 1000000,
          CloseDate: "2022-02-01T05:00:00.000Z",
          NumberOfSharesActual: 100000,
          NumberOfOptionsActual: 0,
          Type: "Equity",
          InterestRate: 0,
          ConvertedToEquity: false,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: 10,
          Currency: "CAD",
          Cap: 0,
          Discount: 0,
          FX: null,
          StrikePrice: 0,
          StrikePriceCurrency: "CAD",
          ConvertibleValue: null,
          NotePriceDifferFromValue: false,
          InterestRateCompounding: "Annually",
          ClassName: "SeriesSeed",
          Series: "N1",
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 1000000,
      total_irr_disp: 80.96882804775534,
      moic: 4.7422128738139095,
      total_remaining_value_disp: 4250987.8738139095,
      total_distributed_all_cos_disp: 491225,
      SharePriceHistory: [
        { SharePrice: 1, Currency: "CAD", Date: "2021-02-01T05:00:00.000Z" },
        { SharePrice: 10, Currency: "USD", Date: "2023-01-11T05:00:00.000Z" },
        { SharePrice: 15, Currency: "USD", Date: "2024-02-16T05:00:00.000Z" },
        { SharePrice: 35, Currency: "USD", Date: "2024-05-14T04:00:00.000Z" },
      ],
      DiscountHistory: [],
      metric_details: [],
      logo_imgurl:
        "https://storage.googleapis.com/freshtracks_public/other/Nvidia-1727718320796.png",
    },
    {
      id: "5513",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "PropertyInvest",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: null,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: "dell.ca",
      ESOPSizeTotal: null,
      Currency: null,
      Industry: "Real Estate",
      Country: "Canada",
      ImpairedDiscount: null,
      tags: [],
      Logo: null,
      company_details: [],
      distributions: [],
      investments: [
        {
          id: "10394",
          __typename: "Investment",
          Name: "BUYPROPERLY LIMITED - SAFE",
          Amount: 50000,
          CloseDate: "2020-09-21T04:00:00.000Z",
          NumberOfSharesActual: null,
          NumberOfOptionsActual: null,
          Type: "SAFE",
          InterestRate: null,
          ConvertedToEquity: null,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: null,
          Currency: "CAD",
          Cap: 5000000,
          Discount: null,
          FX: 1,
          StrikePrice: null,
          StrikePriceCurrency: null,
          ConvertibleValue: null,
          NotePriceDifferFromValue: null,
          InterestRateCompounding: null,
          ClassName: null,
          Series: null,
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 50000,
      total_irr_disp: 0,
      moic: 1,
      total_remaining_value_disp: 50000,
      total_distributed_all_cos_disp: 0,
      SharePriceHistory: [],
      DiscountHistory: [],
      metric_details: [],
      logo_imgurl: "",
    },
    {
      id: "5510",
      __typename: "Company",
      account: {
        id: "562",
        __typename: "Account",
        Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
        Type: "VC",
      },
      Name: "StealthCo",
      Stage: null,
      TotalSharesOutstanding: null,
      LastSharePrice: 0,
      Warrants: null,
      Notes: null,
      Type: "Company",
      url: "dell.com",
      ESOPSizeTotal: null,
      Currency: null,
      Industry: "Software",
      Country: "India",
      ImpairedDiscount: null,
      tags: [
        {
          id: "62",
          __typename: "Tag",
          Name: "AI Focus",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
        {
          id: "64",
          __typename: "Tag",
          Name: "Deep Tech",
          Description: null,
          Use: "Company",
          account: { __typename: "AccountEntity", id: "562" },
        },
      ],
      Logo: {
        id: "1847",
        __typename: "UploadFile",
        url: "https://storage.googleapis.com/freshtracks_public/other/StealthCo-1727718321686.png",
        width: 128,
        height: 128,
      },
      company_details: [
        {
          id: "14490",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5510" },
          EffectiveDate: "2024-02-16T05:00:00.000Z",
          SharePrice: null,
          Discount: null,
          Currency: "CAD",
          CashRemaining: 400000,
          Burn: 200000,
          MRR: 13000,
          Headcount: null,
          ActiveUsers: 11111,
          ActiveCustomers: 33,
          ActiveCustomerDescriptor: null,
          UpdateNote: "Need to fundraise",
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
          MonthsOfRunway: "2.0",
        },
      ],
      distributions: [],
      investments: [
        {
          id: "10390",
          __typename: "Investment",
          Name: "Debenture",
          Amount: 1000001,
          CloseDate: "2021-02-02T05:00:00.000Z",
          NumberOfSharesActual: 0,
          NumberOfOptionsActual: 0,
          Type: "Convertible",
          InterestRate: 6,
          ConvertedToEquity: false,
          ConvertedDate: null,
          Maturity: null,
          PricePerUnit: 0,
          Currency: "CAD",
          Cap: 0,
          Discount: 0,
          FX: null,
          StrikePrice: 0,
          StrikePriceCurrency: "CAD",
          ConvertibleValue: null,
          NotePriceDifferFromValue: false,
          InterestRateCompounding: "Annually",
          ClassName: "SeriesA",
          Series: "N1",
          fund: {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
            fund_banking_details: [
              {
                id: "211",
                __typename: "FundBankingDetail",
                AccountNumber: "",
                Address: "123 Glen St. East",
                EffectiveDate: null,
                Contact: null,
                CreditTo: "",
                Routing: "",
                Swift: "",
                Transit: "",
                Name: "RBC",
                InstitutionCode: "",
                Description: "",
                Country: "United_States_of_America",
                ABA: "",
                funds: [
                  {
                    id: "1070",
                    __typename: "Fund",
                    FundName: "Accent Capital",
                  },
                ],
              },
            ],
            account: {
              id: "562",
              __typename: "Account",
              Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
              Type: "VC",
            },
            gps: [
              {
                id: "127",
                __typename: "Gp",
                Contact: "Alan",
                FirstName: "Alan",
                LastName: "Lysne",
                Phone: "416 555 1212",
                Title: "GP and Founder",
                email: "al@freshtracks.app",
                Logo: null,
              },
            ],
            fund_details: [],
          },
        },
      ],
      asofDate: "2024-10-02T14:29:11.823Z",
      total_inv_disp: 1000001,
      total_irr_disp: 5.999979883205309,
      moic: 1.238125761874238,
      total_remaining_value_disp: 1238127,
      total_distributed_all_cos_disp: 0,
      SharePriceHistory: [],
      DiscountHistory: [],
      metric_details: [
        {
          id: "14490",
          __typename: "CompanyDetail",
          company: { __typename: "CompanyEntity", id: "5510" },
          EffectiveDate: "2024-02-16T05:00:00.000Z",
          SharePrice: null,
          Discount: null,
          Currency: "CAD",
          CashRemaining: 400000,
          Burn: 200000,
          MRR: 13000,
          Headcount: null,
          ActiveUsers: 11111,
          ActiveCustomers: 33,
          ActiveCustomerDescriptor: null,
          UpdateNote: "Need to fundraise",
          FullyDilutedSharesOutstanding: null,
          DiscountToCost: false,
          DiscountFixedValue: null,
          MonthsOfRunway: "2.0",
        },
      ],
      logo_imgurl:
        "https://storage.googleapis.com/freshtracks_public/other/StealthCo-1727718321686.png",
    },
  ],
  fund_info: {
    id: "1070",
    __typename: "Fund",
    FundName: "Accent Capital",
    UnCalledCapitalRemaining: null,
    CashBalance: null,
    CommittedCapital: 16000000,
    Currency: "CAD",
    Url: "a16z.com",
    Logo: {
      id: "1845",
      __typename: "UploadFile",
      url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
      width: 128,
      height: 128,
    },
    fund_banking_details: [
      {
        id: "211",
        __typename: "FundBankingDetail",
        AccountNumber: "",
        Address: "123 Glen St. East",
        EffectiveDate: null,
        Contact: null,
        CreditTo: "",
        Routing: "",
        Swift: "",
        Transit: "",
        Name: "RBC",
        InstitutionCode: "",
        Description: "",
        Country: "United_States_of_America",
        ABA: "",
        funds: [
          {
            id: "1070",
            __typename: "Fund",
            FundName: "Accent Capital",
            UnCalledCapitalRemaining: null,
            CashBalance: null,
            CommittedCapital: null,
            Currency: "CAD",
            Url: "a16z.com",
            Logo: {
              id: "1845",
              __typename: "UploadFile",
              url: "https://storage.googleapis.com/freshtracks_public/other/undefined-1727718319981.png",
              width: 128,
              height: 128,
            },
          },
        ],
      },
    ],
    account: {
      id: "562",
      __typename: "Account",
      Name: "Good Demo Restored-2024-04-11T16:56:29.997Z Restored-2024-09-30T17:45:19.740Z",
      Type: "VC",
    },
    gps: [
      {
        id: "127",
        __typename: "Gp",
        Contact: "Alan",
        FirstName: "Alan",
        LastName: "Lysne",
        Phone: "416 555 1212",
        Title: "GP and Founder",
        email: "al@freshtracks.app",
        Logo: null,
      },
    ],
    fund_details: [],
    asofDate: "2024-10-02T14:29:11.823Z",
  },
  fund_data: [
    {
      label: "2020-10-02T00:00:00.000Z",
      moic: 1.1325199977900418,
      irr: null,
      rvpi: null,
      dvpi: null,
      tvpi: null,
      total_dollars_invested_all_cos: 250000,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 0,
      total_remaining_value_to_lps: 283129.99944751046,
    },
    {
      label: "2021-01-02T00:00:00.000Z",
      moic: 1.1103480075822403,
      irr: null,
      rvpi: null,
      dvpi: null,
      tvpi: null,
      total_dollars_invested_all_cos: 250000,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 0,
      total_remaining_value_to_lps: 277587.00189556007,
    },
    {
      label: "2021-04-02T00:00:00.000Z",
      moic: 1.0282590501562097,
      irr: -54.878853422210106,
      rvpi: 0.642662420477156,
      dvpi: 0,
      tvpi: 0.642662420477156,
      total_dollars_invested_all_cos: 1250001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 1285324.8409543121,
    },
    {
      label: "2021-07-02T00:00:00.000Z",
      moic: 1.032722042089061,
      irr: -38.15151575373324,
      rvpi: 0.7487239968755903,
      dvpi: 0,
      tvpi: 0.7487239968755903,
      total_dollars_invested_all_cos: 1450001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 1497447.9937511806,
    },
    {
      label: "2021-10-02T00:00:00.000Z",
      moic: 1.046131694870547,
      irr: -28.379479298526668,
      rvpi: 0.7584460018469941,
      dvpi: 0,
      tvpi: 0.7584460018469941,
      total_dollars_invested_all_cos: 1450001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 1516892.003693988,
    },
    {
      label: "2022-01-02T00:00:00.000Z",
      moic: 1.05605617178267,
      irr: -21.768477278575915,
      rvpi: 0.7656412525705216,
      dvpi: 0,
      tvpi: 0.7656412525705216,
      total_dollars_invested_all_cos: 1450001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 1531282.5051410433,
    },
    {
      label: "2022-04-02T00:00:00.000Z",
      moic: 0.7485185090670593,
      irr: 19.816575039478003,
      rvpi: 1.1976299887665494,
      dvpi: 0,
      tvpi: 1.1976299887665494,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 2395259.977533099,
    },
    {
      label: "2022-07-02T00:00:00.000Z",
      moic: 0.7545604108264297,
      irr: 16.663750621714325,
      rvpi: 1.2072970346024927,
      dvpi: 0,
      tvpi: 1.2072970346024927,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 2414594.0692049856,
    },
    {
      label: "2022-10-02T00:00:00.000Z",
      moic: 0.762385273233596,
      irr: 14.657151540954994,
      rvpi: 1.2198168183663902,
      dvpi: 0,
      tvpi: 1.2198168183663902,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 2439633.6367327804,
    },
    {
      label: "2023-01-02T00:00:00.000Z",
      moic: 0.7667788852968239,
      irr: 12.936008896189932,
      rvpi: 1.226846599864361,
      dvpi: 0,
      tvpi: 1.226846599864361,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 2453693.1997287218,
    },
    {
      label: "2023-04-02T00:00:00.000Z",
      moic: 1.162207480704638,
      irr: 35.32700857218569,
      rvpi: 1.8595325502311613,
      dvpi: 0,
      tvpi: 1.8595325502311613,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 3719065.1004623226,
    },
    {
      label: "2023-07-02T00:00:00.000Z",
      moic: 1.1586984711485135,
      irr: 30.926480410370583,
      rvpi: 1.8539181331868573,
      dvpi: 0,
      tvpi: 1.8539181331868573,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 3707836.2663737144,
    },
    {
      label: "2023-10-02T00:00:00.000Z",
      moic: 1.175117137640571,
      irr: 28.271140689622285,
      rvpi: 1.8801880077834823,
      dvpi: 0,
      tvpi: 1.8801880077834823,
      total_dollars_invested_all_cos: 3200001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 3760376.0155669646,
    },
    {
      label: "2024-01-02T00:00:00.000Z",
      moic: 1.1644817417200222,
      irr: 26.456131965320175,
      rvpi: 1.9213954560789075,
      dvpi: 0,
      tvpi: 1.9213954560789075,
      total_dollars_invested_all_cos: 3300001,
      total_distributed_to_lps: 0,
      total_distributed_all_cos: 0,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 3842790.912157815,
    },
    {
      label: "2024-04-02T00:00:00.000Z",
      moic: 1.5376865418025492,
      irr: 31.21969113073282,
      rvpi: 2.2871835628174773,
      dvpi: 0.027944,
      tvpi: 2.315127562817477,
      total_dollars_invested_all_cos: 3300001,
      total_distributed_to_lps: 55888,
      total_distributed_all_cos: 500000,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 4574367.125634954,
    },
    {
      label: "2024-07-02T00:00:00.000Z",
      moic: 2.456427774892687,
      irr: 46.61311890374187,
      rvpi: 3.5574945567868212,
      dvpi: 0.027944,
      tvpi: 3.5854385567868214,
      total_dollars_invested_all_cos: 3300001,
      total_distributed_to_lps: 55888,
      total_distributed_all_cos: 991225,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 7114989.113573642,
    },
    {
      label: "2024-10-02T00:00:00.000Z",
      moic: 2.4379937672164345,
      irr: 42.41953481623526,
      rvpi: 3.5270169349040006,
      dvpi: 0.027944,
      tvpi: 3.554960934904001,
      total_dollars_invested_all_cos: 3300001,
      total_distributed_to_lps: 55888,
      total_distributed_all_cos: 991348,
      total_paid_in_capital: 2000000,
      total_remaining_value_to_lps: 7054033.869808001,
    },
  ],
  format: "pptx",
  donutChart_base64:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==",
  donutChart_url:
    "https://quickchart.io/chart?w=700&h=600&v=4&c=%7Boptions%3A%20%7B%22legend%22%3A%7B%22labels%22%3A%7B%7D%7D%2C%22scales%22%3A%7B%22y%22%3A%7B%22type%22%3A%22linear%22%2C%22display%22%3Atrue%2C%22position%22%3A%22left%22%7D%2C%22y1%22%3A%7B%22type%22%3A%22linear%22%2C%22display%22%3Atrue%2C%22position%22%3A%22right%22%2C%22grid%22%3A%7B%22drawOnChartArea%22%3Afalse%7D%7D%7D%2C%22maintainAspectRatio%22%3Afalse%7D%2Ctype%3A%27line%27%2Cdata%3A%7B%22labels%22%3A%5B%2220-10-02%22%2C%2221-01-02%22%2C%2221-04-02%22%2C%2221-07-02%22%2C%2221-10-02%22%2C%2222-01-02%22%2C%2222-04-02%22%2C%2222-07-02%22%2C%2222-10-02%22%2C%2223-01-02%22%2C%2223-04-02%22%2C%2223-07-02%22%2C%2223-10-02%22%2C%2224-01-02%22%2C%2224-04-02%22%2C%2224-07-02%22%2C%2224-10-02%22%5D%2C%22datasets%22%3A%5B%7B%22label%22%3A%22Total%20Remaining%20(LP)%22%2C%22backgroundColor%22%3A%22%234c7c9b%22%2C%22fill%22%3Atrue%2C%22data%22%3A%5B283129.99944751046%2C277587.00189556007%2C1285324.8409543121%2C1497447.9937511806%2C1516892.003693988%2C1531282.5051410433%2C2395259.977533099%2C2414594.0692049856%2C2439633.6367327804%2C2453693.1997287218%2C3719065.1004623226%2C3707836.2663737144%2C3760376.0155669646%2C3842790.912157815%2C4574367.125634954%2C7114989.113573642%2C7054033.869808001%5D%2C%22cubicInterpolationMode%22%3A%22monotone%22%2C%22tension%22%3A0.4%2C%22yAxisID%22%3A%22y%22%7D%2C%7B%22label%22%3A%22Total%20Distributed%20(LP)%22%2C%22backgroundColor%22%3A%22%2386b0cc%22%2C%22data%22%3A%5B0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C0%2C55888%2C55888%2C55888%5D%2C%22fill%22%3Atrue%2C%22cubicInterpolationMode%22%3A%22monotone%22%2C%22tension%22%3A0.4%2C%22yAxisID%22%3A%22y%22%7D%2C%7B%22label%22%3A%22Total%20Paid%20In%20Capital%20(LP)%22%2C%22backgroundColor%22%3A%22%23004c6d%22%2C%22data%22%3A%5B0%2C0%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%2C2000000%5D%2C%22fill%22%3Atrue%2C%22cubicInterpolationMode%22%3A%22monotone%22%2C%22tension%22%3A0.4%2C%22yAxisID%22%3A%22y%22%7D%2C%7B%22label%22%3A%22IRR%20(LP)%22%2C%22backgroundColor%22%3A%22%23c1e7ff%22%2C%22data%22%3A%5Bnull%2Cnull%2C-54.878853422210106%2C-38.15151575373324%2C-28.379479298526668%2C-21.768477278575915%2C19.816575039478003%2C16.663750621714325%2C14.657151540954994%2C12.936008896189932%2C35.32700857218569%2C30.926480410370583%2C28.271140689622285%2C26.456131965320175%2C31.21969113073282%2C46.61311890374187%2C42.41953481623526%5D%2C%22fill%22%3Atrue%2C%22cubicInterpolationMode%22%3A%22monotone%22%2C%22tension%22%3A0.4%2C%22borderWidth%22%3A4%2C%22borderColor%22%3A%22%23c1e7ff%22%2C%22yAxisID%22%3A%22y1%22%7D%5D%7D%7D",
};

module.exports = data;
